### ISSUE TITLE
Fread() Serial error line 92

### ISSUE THREAD

**Issue by freemann** [DirkEngels/PlugWeb-Driver#1]
First i got a directory error, i solved this by moving the driver directory up in the tree.

Now i get:
[Tue Feb 07 21:21:02 2012] [error] [client 127.0.0.1] PHP Warning:  fread() expects parameter 1 to be resource, boolean given in /home/marco/www/PlugWeb-Driver/lib/PlugWeb/Driver/Serial.php on line 92

I get this error with the following code:
<code>
error_reporting(E_ALL);
ini_set('display_errors', '3');

include('bootstrap.php');

// Example mac addresses
$mac = 'C3XXXC'; //mac (normal) Circle
$macStick = '75XXX8'; //mac Stick

// Initialize stick
$device = new \PlugWeb\Driver\Device($mac, '/dev/ttyUSB0');
$device->initStick();

// Keep switching the light on and off with pauses of 3 seconds
while (true) {
    $device->powerSwitch(true);
    sleep(3);
    $device->powerSwitch(false);
    sleep(3);
}
</code> 

Hope you can help me.

**Comment by freemann** [comment]
Both issue i opened where solved by reboot the computer/ubuntu.
linux/my computer  or Ubuntu has problems with reconnecting to the plugwise stick. 

This happens  when my computer came out of suspend mode OR i disconnect/reconnect the plugwise stick from the usbport.

**Comment by DirkEngels** [comment]
Hi Freeman,

 Verify that your plugwise stick is registered at the specified device 
 name. Execute the following command to see which usb devices have been 
 registered:

 ls -al /dev/ttyUSB*

 Try changing the script below in such a way that it will be using 
 /dev/ttyUSB\* device as found with the previous command.

 Dirk Engels

**Comment by freemann** [comment]
Hi Dirk,

Thanx for the response!
As mentioned above, i already "solved" the problem.

Also I found that (on my ubuntu system) the Plugwise stick is available with the following "devicename"
/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A700gCFR-if00-port0

This probably is a generic name and can be used as a standard value in the driver.

I'm now working on a Jquery ajaxify "GUI". When its "ready" i'll post it somewhere in you project.
